module.exports = {
  uz: {
    flag: '🇺🇿', name: "O'zbek",
    welcome: (name) => `👋 Salom, *${name}*!\n\n🧹 Men sizning Telegram akkauntingizni keraksiz kanal, guruh va botlardan tozalashga yordam beraman.\n\n🌐 Tilni tanlang:`,
    choose_lang: '🌐 Tilni tanlang:',
    subscribe_required: (channel) => `📢 Botdan foydalanish uchun kanalga obuna bo'ling:\n\n${channel}`,
    subscribed_btn: '✅ Obuna bo\'ldim',
    check_sub: '🔄 Tekshirish',
    not_subscribed: '❌ Siz hali obuna bo\'lmagansiz! Iltimos, obuna bo\'ling va "Tekshirish" tugmasini bosing.',
    connect_account: '🔗 Akkauntni ulash',
    enter_phone: '📞 Telefon raqamingizni kiriting (masalan: +998901234567):',
    sending_code: '⏳ Kod yuborilmoqda...',
    enter_code: '📩 Telegramdan kelgan 5 raqamli kodni kiriting:',
    enter_2fa: '🔐 2FA parolingizni kiriting:',
    connected: (name) => `✅ *${name}* akkauntingiz ulandi!\n\nNimani skanerlashni xohlaysiz?`,
    already_connected: (phone) => `✅ Akkaunt allaqachon ulangan: *${phone}*\n\nNimani skanerlashni xohlaysiz?`,
    scanning: '🔍 Skanerlash boshlandi, iltimos kuting...',
    scan_channels: '📢 Kanallar',
    scan_groups: '👥 Guruhlar',
    scan_bots: '🤖 Botlar',
    scan_all: '🔍 Hammasini skaner',
    found: (count, type) => `📋 *${type}* topildi: *${count}* ta\n\nChiqmoqchi bo'lganlaringizni tanlang yoki hammasidan chiqing:`,
    leave_all: '🗑 Hammasidan chiq',
    back: '🔙 Ortga',
    leaving_all: (count) => `⏳ ${count} ta dan chiqilmoqda... Iltimos kuting.`,
    done: (ok, fail) => `✅ *Tugadi!*\n\n✔️ Chiqildi: *${ok}* ta\n❌ Xato: *${fail}* ta`,
    left_msg: (title) => `✅ *${title}* dan chiqildi!`,
    error: (msg) => `❌ Xato: ${msg}`,
    not_connected: '❌ Avval akkauntingizni ulang!',
    nothing: (type) => `✅ Hech qanday ${type} topilmadi.`,
    disconnect: '🔌 Akkauntni uzish',
    disconnect_confirm: '⚠️ Haqiqatan ham akkauntni uzmoqchimisiz?',
    disconnect_yes: '✅ Ha, uzish',
    disconnect_no: '❌ Bekor qilish',
    disconnected: '✅ Akkaunt uzildi.',
    main_menu: '🏠 Bosh menyu',
    settings: '⚙️ Sozlamalar',
    help: '❓ Yordam',
    help_text: `❓ *Yordam*\n\n1. Akkauntingizni ulang (telefon raqam va SMS kod)\n2. Skanerlash turini tanlang\n3. Ro'yxatdan chiqmoqchilarni tanlang\n4. Yoki "Hammasidan chiq" tugmasi bilan tozalang\n\n⚠️ *Eslatma:* Telegram limitlari tufayli "Hammasidan chiq" biroz vaqt olishi mumkin.`,
    banned: '🚫 Siz botdan bloklangansiz.',
    cancel: '❌ Bekor qilish',
    wrong_input: '⚠️ Noto\'g\'ri format. Qaytadan kiriting:',
  },

  ru: {
    flag: '🇷🇺', name: 'Русский',
    welcome: (name) => `👋 Привет, *${name}*!\n\n🧹 Я помогу очистить ваш Telegram аккаунт от ненужных каналов, групп и ботов.\n\n🌐 Выберите язык:`,
    choose_lang: '🌐 Выберите язык:',
    subscribe_required: (channel) => `📢 Подпишитесь на канал для использования бота:\n\n${channel}`,
    subscribed_btn: '✅ Я подписался',
    check_sub: '🔄 Проверить',
    not_subscribed: '❌ Вы ещё не подписаны! Подпишитесь и нажмите "Проверить".',
    connect_account: '🔗 Подключить аккаунт',
    enter_phone: '📞 Введите номер телефона (например: +998901234567):',
    sending_code: '⏳ Отправка кода...',
    enter_code: '📩 Введите 5-значный код из Telegram:',
    enter_2fa: '🔐 Введите пароль 2FA:',
    connected: (name) => `✅ Аккаунт *${name}* подключён!\n\nЧто сканировать?`,
    already_connected: (phone) => `✅ Аккаунт уже подключён: *${phone}*\n\nЧто сканировать?`,
    scanning: '🔍 Сканирование началось, подождите...',
    scan_channels: '📢 Каналы',
    scan_groups: '👥 Группы',
    scan_bots: '🤖 Боты',
    scan_all: '🔍 Сканировать всё',
    found: (count, type) => `📋 *${type}* найдено: *${count}*\n\nВыберите для выхода или выйдите из всех:`,
    leave_all: '🗑 Выйти из всех',
    back: '🔙 Назад',
    leaving_all: (count) => `⏳ Выхожу из ${count}... Подождите.`,
    done: (ok, fail) => `✅ *Готово!*\n\n✔️ Успешно: *${ok}*\n❌ Ошибки: *${fail}*`,
    left_msg: (title) => `✅ Вышел из *${title}*!`,
    error: (msg) => `❌ Ошибка: ${msg}`,
    not_connected: '❌ Сначала подключите аккаунт!',
    nothing: (type) => `✅ Нет ${type}.`,
    disconnect: '🔌 Отключить аккаунт',
    disconnect_confirm: '⚠️ Вы уверены, что хотите отключить аккаунт?',
    disconnect_yes: '✅ Да, отключить',
    disconnect_no: '❌ Отмена',
    disconnected: '✅ Аккаунт отключён.',
    main_menu: '🏠 Главное меню',
    settings: '⚙️ Настройки',
    help: '❓ Помощь',
    help_text: `❓ *Помощь*\n\n1. Подключите аккаунт (телефон + код)\n2. Выберите тип сканирования\n3. Отметьте ненужные или выйдите из всех\n\n⚠️ *Примечание:* "Выйти из всех" может занять время из-за лимитов Telegram.`,
    banned: '🚫 Вы заблокированы.',
    cancel: '❌ Отмена',
    wrong_input: '⚠️ Неверный формат. Введите заново:',
  },

  en: {
    flag: '🇬🇧', name: 'English',
    welcome: (name) => `👋 Hello, *${name}*!\n\n🧹 I'll help you clean your Telegram account from unwanted channels, groups and bots.\n\n🌐 Choose language:`,
    choose_lang: '🌐 Choose language:',
    subscribe_required: (channel) => `📢 Please subscribe to use the bot:\n\n${channel}`,
    subscribed_btn: '✅ I subscribed',
    check_sub: '🔄 Check',
    not_subscribed: '❌ You are not subscribed! Subscribe and press "Check".',
    connect_account: '🔗 Connect Account',
    enter_phone: '📞 Enter your phone number (e.g. +998901234567):',
    sending_code: '⏳ Sending code...',
    enter_code: '📩 Enter the 5-digit code from Telegram:',
    enter_2fa: '🔐 Enter your 2FA password:',
    connected: (name) => `✅ Account *${name}* connected!\n\nWhat to scan?`,
    already_connected: (phone) => `✅ Account already connected: *${phone}*\n\nWhat to scan?`,
    scanning: '🔍 Scanning started, please wait...',
    scan_channels: '📢 Channels',
    scan_groups: '👥 Groups',
    scan_bots: '🤖 Bots',
    scan_all: '🔍 Scan All',
    found: (count, type) => `📋 *${type}* found: *${count}*\n\nSelect to leave or leave all:`,
    leave_all: '🗑 Leave All',
    back: '🔙 Back',
    leaving_all: (count) => `⏳ Leaving ${count} items... Please wait.`,
    done: (ok, fail) => `✅ *Done!*\n\n✔️ Left: *${ok}*\n❌ Failed: *${fail}*`,
    left_msg: (title) => `✅ Left *${title}*!`,
    error: (msg) => `❌ Error: ${msg}`,
    not_connected: '❌ Connect your account first!',
    nothing: (type) => `✅ No ${type} found.`,
    disconnect: '🔌 Disconnect Account',
    disconnect_confirm: '⚠️ Are you sure you want to disconnect?',
    disconnect_yes: '✅ Yes, disconnect',
    disconnect_no: '❌ Cancel',
    disconnected: '✅ Account disconnected.',
    main_menu: '🏠 Main Menu',
    settings: '⚙️ Settings',
    help: '❓ Help',
    help_text: `❓ *Help*\n\n1. Connect your account (phone + code)\n2. Choose scan type\n3. Select to leave or leave all\n\n⚠️ *Note:* "Leave All" may take time due to Telegram limits.`,
    banned: '🚫 You are banned.',
    cancel: '❌ Cancel',
    wrong_input: '⚠️ Wrong format. Try again:',
  },
};
